[build]
  functions = "netlify-functions"  # Folder where serverless functions will go
  publish = "public"               # Folder with static files to be served

[dev]
  functions = "netlify-functions"
  publish = "public"
  port = 3002
